name: Update Mensa Calendar

on:
  schedule:
    # Run daily at 5:00 AM UTC
    - cron: '0 5 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate calendar
      run: python main.py
      
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add mensa.ics
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update mensa calendar - $(date)"
          git push
        fi
